name: sp_2021
description: SPTOFT2021

publish_to: 'none'

version: 2.0.9+19

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  path_provider: ^1.6.24

  animate_do: ^1.7.5
  data_connection_checker: ^0.3.4
  dartz: ^0.9.2
  fuzzy: ^0.3.0
  flutter_bloc: ^6.1.1
  get_it: ^5.0.3
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  cached_network_image: ^2.2.0+1
  auto_size_text_field: ^0.1.7

  flare_flutter: ^2.0.6
  package_info: ^0.4.3+2

  equatable: ^1.2.0
  dio: ^3.0.9
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.0+1

  fluttertoast: ^7.1.6
  pattern_formatter: ^1.0.2
  flutter_progress_button: ^1.0.0

  image_picker: ^0.6.7+17
  intl: ^0.16.1

  google_maps_flutter: ^1.0.6
  location: ^3.0.0

  ntp: ^1.0.7

  percent_indicator: ^2.1.8
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.12+4

  uuid: ^2.2.2
  ota_update: ^2.4.1
  ext_storage: ^1.0.3
  wakelock: ^0.2.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  build_runner: ^1.10.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: FuturaMd
      fonts:
        - asset: assets/fonts/FuturaMd.ttf
    - family: UTMBebas
      fonts:
        - asset: assets/fonts/UTM Bebas.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
